# -*- coding: utf-8 -*-
"""PDILab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10y09-6FrX2tiPdkZ2wXv6gIksx3wRtds

#Importar librerias
"""

!pip install opencv-python
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

"""##Cargar video

"""

uploaded = files.upload()

video_path = "CarroNocortado.mp4"   # cambia por el nombre real

"""#Ejemplo con video cortado

"""

cap = cv2.VideoCapture(video_path)

fps = cap.get(cv2.CAP_PROP_FPS)
print("FPS:", fps)

fgbg = cv2.createBackgroundSubtractorMOG2()

from google.colab.patches import cv2_imshow
centroides = []

while True:

    ret, frame = cap.read()

    if not ret:
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    fgmask = fgbg.apply(gray)

    cv2_imshow(fgmask) # Changed cv2.imshow to cv2_imshow

    if cv2.waitKey(30) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()

kernel = np.ones((5,5),np.uint8)

mask = cv2.morphologyEx(fgmask, cv2.MORPH_OPEN, kernel)
mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)

contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

if contours:

    largest = max(contours, key=cv2.contourArea)

M = cv2.moments(largest)

if M["m00"] != 0:

    cx = int(M["m10"] / M["m00"])
    cy = int(M["m01"] / M["m00"])

    centroides.append((cx, cy))

cap = cv2.VideoCapture(video_path)

from google.colab.patches import cv2_imshow

# --- Variables para recortar el video ---
# Ajusta estos valores para recortar tu video.
# y_inicio y y_fin controlan el recorte vertical (alto).
# x_inicio y x_fin controlan el recorte horizontal (ancho).
# La resolución original es 1280x720.
y_inicio = 390    # Inicio del recorte vertical (fila superior)
y_fin = 720     # Fin del recorte vertical (fila inferior)
x_inicio = 0    # Inicio del recorte horizontal (columna izquierda)
x_fin = 1280    # Fin del recorte horizontal (columna derecha)

while True:

    ret, frame = cap.read()

    if not ret:
        break

    # Recortar el frame
    frame = frame[y_inicio:y_fin, x_inicio:x_fin]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    fgmask = fgbg.apply(gray)

    contours, _ = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:

        largest = max(contours, key=cv2.contourArea)

        M = cv2.moments(largest)

        if M["m00"] != 0:

            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])

            cv2.circle(frame, (cx,cy), 6, (0,0,255), -1)

            cv2.drawContours(frame, [largest], -1, (0,255,0), 2)

            texto = f"Centroide ({cx},{cy})"

            cv2.putText(frame, texto, (cx+10,cy-10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (0,0,0),
                        2)

    cv2_imshow(frame)

cap.release()



"""### Detección de Centroides y Dibujo de Trayectoria"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
video_path = "CarroNocortado.mp4" # <-- Agregado para definir video_path
cap = cv2.VideoCapture(video_path)
fgbg = cv2.createBackgroundSubtractorMOG2() # <-- Agregado para inicializar fgbg


from google.colab.patches import cv2_imshow

centroides = []

# Variables de recorte (tomadas de la celda anterior para consistencia)
y_inicio = 390
y_fin = 720
x_inicio = 0
x_fin = 1280

while True:

    ret, frame = cap.read()

    if not ret:
        break

    # Recortar el frame
    frame = frame[y_inicio:y_fin, x_inicio:x_fin]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    fgmask = fgbg.apply(gray)

    contours, _ = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:

        largest = max(contours, key=cv2.contourArea)

        M = cv2.moments(largest)

        if M["m00"] != 0:

            cx = int(M["m10"] / M["m00"])
            cy = int(M["m01"] / M["m00"])

            centroides.append((cx, cy))

            # Dibujar el círculo del centroide actual
            cv2.circle(frame, (cx, cy), 6, (0, 0, 255), -1)

            # Dibujar la trayectoria (líneas entre centroides)
            for i in range(1, len(centroides)):
                cv2.line(frame, centroides[i-1], centroides[i], (0, 255, 0), 2)

            # Dibujar el contorno del objeto detectado
            cv2.drawContours(frame, [largest], -1, (0, 255, 0), 2)

            texto = f"Centroide ({cx},{cy})"

            cv2.putText(frame, texto, (cx+10, cy-10),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        0.6,
                        (0, 0, 0),
                        2)

    cv2_imshow(frame)

cap.release()

"""# 1. OBJETIVO

El objetivo de este proyecto es analizar el movimiento de un vehículo a partir de un video grabado por el grupo de trabajo, utilizando técnicas de procesamiento digital de imágenes y visión por computadora. Se aplicarán conceptos de segmentación, morfología, detección de contornos, cálculo de centroides y derivación numérica para estimar en cada instante de tiempo la posición, velocidad y aceleración del vehículo, comparando los resultados obtenidos con modelos cinemáticos teóricos.

# 2. DESCRIPCIÓN GENERAL

El grupo deberá grabar, procesar y analizar un video en el que un vehículo (automóvil, motocicleta, bus u otro) se desplace entre dos puntos A y B con movimiento visible y continuo. A partir del video, se extraerán los parámetros cinemáticos del movimiento aplicando las herramientas de PDI vistas en clase. El vehículo deberá ser segmentado cuadro a cuadro del fondo de la escena para permitir el cálculo de su centroide y su posición a lo largo del tiempo.

## PUNTO 1 (10%) - Grabación del Video

Grabe un video en el que un vehículo se desplace entre dos puntos A y B. Coloque marcadores visuales (conos, líneas pintadas u objetos de referencia) en el inicio y el final del recorrido para poder definir la escala de la escena (píxeles a metros). Requisitos del video: vista lateral fija (cámara estática), iluminación adecuada, duración mínima de 5 segundos, resolución mínima 720p a 30 fps, fondo lo más homogéneo posible.
"""



"""## PUNTO 2 (40%) - Detección y Segmentación del Vehículo

Esta sección implementa los pasos para detectar y segmentar el vehículo en cada fotograma del video. Incluye:
- **Conversión a escala de grises:** Para facilitar la segmentación.
- **Sustracción de fondo (background subtraction):** Para aislar el vehículo en movimiento.
- **Operaciones morfológicas (apertura y cierre):** Para limpiar la máscara del vehículo y eliminar ruido.
- **Detección de contornos:** Para identificar las formas de los objetos en movimiento.
- **Cálculo del centroide:** Para determinar la posición del vehículo en cada fotograma.

### 2.1 Configuración Inicial para Detección y Segmentación
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Definir la ruta del video (asegúrate de que este archivo esté cargado en Colab)
video_path = "CarroNocortado.mp4" # Definición de la ruta del video

# Inicializar la captura de video
cap = cv2.VideoCapture(video_path)

# Inicialización del sustractor de fondo
fgbg = cv2.createBackgroundSubtractorMOG2()

# Lista para almacenar los centroides del vehículo
centroides = []

# --- Variables para definir la Región de Interés (ROI) ---
# Estas coordenadas definen la zona donde nos interesa detectar el vehículo.
# Todo lo que esté fuera de esta zona será ignorado en el procesamiento.
# La resolución original del video es 1280x720.
y_inicio = 406    # Inicio del recorte vertical (fila superior) de la ROI
y_fin = 675       # Fin del recorte vertical (fila inferior) de la ROI
x_inicio = 9      # Inicio del recorte horizontal (columna izquierda) de la ROI
x_fin = 1280      # Fin del recorte horizontal (columna derecha) de la ROI

# Definir el kernel para las operaciones morfológicas
kernel = np.ones((7,7),np.uint8)

# Umbral mínimo de área para los contornos (en píxeles cuadrados)
min_contour_area = 500  # Ignora objetos menores a 500 píxeles cuadrados

"""### 2.2 Bucle de Procesamiento de Video (Detección y Tracking)

---


"""

# Este bucle utiliza las variables inicializadas en la celda '2.1 Configuración Inicial'
while True:

    ret, frame = cap.read()

    if not ret:
        break

    # Crear una copia del frame original para dibujar sobre ella
    frame_display = frame.copy()

    # 1. Conversión a escala de grises (aplicada al frame completo)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 2. Sustracción de fondo (aplicada al frame completo en escala de grises)
    fgmask = fgbg.apply(gray)

    # 3. Operaciones morfológicas para limpiar la máscara (aplicadas al fgmask completo)
    mask_limpia = cv2.morphologyEx(fgmask, cv2.MORPH_OPEN, kernel)
    mask_limpia = cv2.morphologyEx(mask_limpia, cv2.MORPH_CLOSE, kernel)

    # --- Aplicar la Región de Interés (ROI) a la máscara limpia ---
    # Creamos una máscara de ceros del mismo tamaño que mask_limpia
    roi_mask_region = np.zeros(mask_limpia.shape, dtype=np.uint8)
    # Dibujamos un rectángulo blanco (255) dentro de nuestra ROI
    roi_mask_region[y_inicio:y_fin, x_inicio:x_fin] = 255
    # Aplicamos esta máscara a mask_limpia. Todo lo que esté fuera de la ROI se volverá negro.
    mask_limpia = cv2.bitwise_and(mask_limpia, roi_mask_region)

    # Convertir mask_limpia (ahora con la ROI aplicada) a BGR para poder concatenarla y mostrarla
    mask_limpia_bgr = cv2.cvtColor(mask_limpia, cv2.COLOR_GRAY2BGR)

    # 4. Detección de contornos (solo detectará contornos dentro de la ROI debido a la máscara)
    contours, _ = cv2.findContours(mask_limpia, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:

        # Encontrar el contorno más grande que sea mayor al área mínima
        largest_contour = None
        max_area = 0
        for contour in contours:
            area = cv2.contourArea(contour)
            # Aseguramos que el contorno esté dentro de la ROI (aunque la máscara ya lo filtra, es una doble verificación)
            # y que sea mayor al área mínima
            if area > min_contour_area and area > max_area:
                # Aquí podríamos añadir una comprobación de que el centroide del contorno esté dentro de la ROI
                # pero la máscara ya hace gran parte del trabajo.
                largest_contour = contour
                max_area = area

        if largest_contour is not None:

            # 5. Cálculo del centroide del vehículo
            M = cv2.moments(largest_contour)

            if M["m00"] != 0:

                cx = int(M["m10"] / M["m00"])
                cy = int(M["m01"] / M["m00"])

                centroides.append((cx, cy))

                # --- Dibujo en el frame_display original para visualización ---
                # Dibujar el círculo del centroide actual
                cv2.circle(frame_display, (cx, cy), 6, (0, 0, 255), -1) # Color rojo para el centroide

                # Dibujar la trayectoria (líneas entre centroides)
                for i in range(1, len(centroides)):
                    cv2.line(frame_display, centroides[i-1], centroides[i], (0, 255, 0), 2) # Color verde para la trayectoria

                # Dibujar el contorno del objeto detectado
                cv2.drawContours(frame_display, [largest_contour], -1, (255, 0, 0), 2) # Color azul para el contorno

                texto = f"Centroide ({cx},{cy})"

                cv2.putText(frame_display, texto, (cx+10, cy-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.6,
                            (0, 0, 0),
                            2) # Color negro para el texto

    # Concatenar el frame original con los dibujos y la máscara procesada para mostrarlos juntos
    concatenated_frames = cv2.hconcat([frame_display, mask_limpia_bgr])

    cv2_imshow(concatenated_frames)

cap.release()

"""### Script para selección de ROI local (ejecutar en tu máquina local)"""

# Guarda este código en un archivo .py y ejecútalo localmente.

#import cv2
#
## Reemplaza 'Carro.mp4' con la ruta a tu archivo de video local
#video_path_local = 'Carro.mp4'
#
#cap_local = cv2.VideoCapture(video_path_local)
#
#if not cap_local.isOpened():
#    print(f"Error: No se pudo abrir el video en {video_path_local}")
#    exit()
#
## Lee el primer fotograma
#ret_local, frame_local = cap_local.read()
#
#if not ret_local:
#    print("Error: No se pudo leer el primer fotograma del video.")
#    cap_local.release()
#    exit()
#
## Selecciona la ROI interactivamente
## La función selectROI devuelve (x, y, w, h)
## Puedes arrastrar un rectángulo y pulsar ENTER para confirmar
## o 'c' para cancelar.
#print("Selecciona la región de interés (ROI) en la ventana que aparecerá y pulsa ENTER.")
#bbox = cv2.selectROI("Seleccionar ROI", frame_local, False, False)
#
#x_local, y_local, w_local, h_local = bbox
#
#if w_local > 0 and h_local > 0:
#    print(f"Coordenadas de la ROI seleccionada:")
#    print(f"  x_inicio = {x_local}")
#    print(f"  y_inicio = {y_local}")
#    print(f"  x_fin = {x_local + w_local}")
#    print(f"  y_fin = {y_local + h_local}")
#    print("\nUsa estos valores en la celda del Colab para recortar tu video.")
#else:
#    print("No se seleccionó ninguna ROI. Los valores predeterminados serán usados.")
#
#cv2.destroyAllWindows()
#cap_local.release()
#

"""## PUNTO 3 (30%) - Análisis Cinemático del Movimiento

Esta sección se dedicará al análisis cuantitativo del movimiento del vehículo, extrayendo parámetros cinemáticos y comparándolos con modelos teóricos.

### 3.1. Posición del centroide en función del tiempo

Aquí se calculará la posición del centroide (tanto en píxeles como en metros) en función del tiempo. Necesitarás establecer una escala de píxeles a metros utilizando los marcadores visuales que colocaste en el video.
"""

# Implementación para el cálculo de la posición y la escala

# Escala: Define la relación entre píxeles y metros
# Para un coche de 3.815 metros que mide 302 píxeles en el video:
escala_px_a_metros = 3.815 / 302  # metros por píxel

# Extraer las coordenadas 'x' de los centroides (asumiendo movimiento principal en x)
# Los centroides se acumulan en la ejecución de la celda eacd5332 (Punto 2)
posiciones_x_px_raw = [c[0] for c in centroides]

# --- Eliminar el primer centroide si la lista tiene al menos 2 elementos ---
# Esto es para evitar un centroide potencialmente erróneo al inicio.
if len(posiciones_x_px_raw) > 1:
    posiciones_x_px_raw = posiciones_x_px_raw[1:]
    print("Advertencia: El primer centroide ha sido eliminado para el análisis cinemático.")
elif len(posiciones_x_px_raw) == 1:
    print("Advertencia: Solo se detectó un centroide, el análisis cinemático será limitado.")
else:
    print("Error: No se detectaron centroides para el análisis cinemático.")

# --- Transformar las posiciones para que el eje x sea creciente (de 'abajo a arriba') ---
# Si las posiciones originales disminuyen (carro de derecha a izquierda),
# restamos de la posición máxima para que la posición relativa aumente.
if len(posiciones_x_px_raw) > 0:
    max_x_px = max(posiciones_x_px_raw)
    posiciones_x_px = [max_x_px - x for x in posiciones_x_px_raw]
else:
    posiciones_x_px = [] # Mantener la lista vacía si no hay centroides


# Reabrir el video para obtener el FPS, ya que cap.release() puede haberlo cerrado
cap_for_fps = cv2.VideoCapture(video_path)
if not cap_for_fps.isOpened():
    print("Error: No se pudo abrir el video para obtener el FPS.")
    fps = 30.0 # Valor por defecto si no se puede abrir
else:
    fps = cap_for_fps.get(cv2.CAP_PROP_FPS)
    cap_for_fps.release() # Liberar el objeto de captura después de obtener el FPS

# Si por alguna razón fps es 0, asignarle un valor por defecto para evitar ZeroDivisionError
if fps == 0:
    print("Advertencia: FPS detectado como 0, usando 30.0 como valor por defecto.")
    fps = 30.0

# Calcular el tiempo para cada fotograma
tiempo = np.arange(len(posiciones_x_px)) / fps

# Convertir posiciones a metros
posiciones_x_metros = np.array(posiciones_x_px) * escala_px_a_metros

# Imprimir o mostrar los resultados
print("Escala (metros/píxel):", escala_px_a_metros)
print("Primeros 5 posiciones en píxeles (x - transformadas):")
print(posiciones_x_px[:5])
print("Primeros 5 posiciones en metros (x - transformadas):")
print(posiciones_x_metros[:5])
print("Primeros 5 instantes de tiempo (s):")
print(tiempo[:5])

"""### 3.2. Velocidad instantánea

Cálculo de la velocidad instantánea del vehículo utilizando diferencias finitas hacia adelante entre fotogramas consecutivos.
"""

# Implementación para el cálculo de la velocidad instantánea en metros/segundo

delta_t = 1 / fps
velocidades_metros_s = np.diff(posiciones_x_metros) / delta_t

# Para igualar la longitud con las posiciones, se añade el último valor o un cero al final.
# Esto es útil para graficar con el mismo array de tiempo que las posiciones.
velocidades_metros_s_graficar = np.append(velocidades_metros_s, velocidades_metros_s[-1] if velocidades_metros_s.size > 0 else 0)

print("Primeros 5 velocidades en m/s:")
print(velocidades_metros_s_graficar[:5])

"""### 3.3. Aceleración instantánea

Cálculo de la aceleración instantánea como la segunda derivada numérica de la posición.
"""

# Implementación para el cálculo de la aceleración instantánea en metros/segundo²

delta_t = 1 / fps
aceleraciones_metros_s2 = np.diff(velocidades_metros_s) / delta_t

# Para igualar la longitud con las velocidades, se añade el último valor o un cero al final.
aceleraciones_metros_s2_graficar = np.append(aceleraciones_metros_s2, aceleraciones_metros_s2[-1] if aceleraciones_metros_s2.size > 0 else 0)

print("Primeros 5 aceleraciones en m/s²:")
print(aceleraciones_metros_s2_graficar[:5])

"""### 3.4. Gráficas de posición, velocidad y aceleración vs. tiempo

Visualización de los resultados obtenidos.
"""

import matplotlib.pyplot as plt

# Graficar Posición vs. Tiempo
plt.figure(figsize=(12, 4))
plt.plot(tiempo, posiciones_x_metros, marker='.', linestyle='-')
plt.title('Posición vs. Tiempo')
plt.xlabel('Tiempo (s)')
plt.ylabel('Posición (m)')
plt.grid(True)
plt.show()

# Graficar Velocidad vs. Tiempo
# Ajustar el array de tiempo para la velocidad para que coincida en longitud
tiempo_velocidad = tiempo[:len(velocidades_metros_s)]
plt.figure(figsize=(12, 4))
plt.plot(tiempo_velocidad, velocidades_metros_s, marker='.', linestyle='-')
plt.title('Velocidad vs. Tiempo')
plt.xlabel('Tiempo (s)')
plt.ylabel('Velocidad (m/s)')
plt.grid(True)
plt.show()

# Graficar Aceleración vs. Tiempo
# Ajustar el array de tiempo para la aceleración
tiempo_aceleracion = tiempo[:len(aceleraciones_metros_s2)]
plt.figure(figsize=(12, 4))
plt.plot(tiempo_aceleracion, aceleraciones_metros_s2, marker='.', linestyle='-')
plt.title('Aceleración vs. Tiempo')
plt.xlabel('Tiempo (s)')
plt.ylabel('Aceleración (m/s²)')
plt.grid(True)
plt.show()

"""### 3.5. Comparación con modelo cinemático teórico

Comparación de los resultados experimentales con el modelo cinemático teórico correspondiente (MRUA u otro) e identificación del tipo de movimiento del vehículo.
"""

# Aquí puedes comparar tus datos experimentales con un modelo teórico (por ejemplo, MRUA).
# Por ejemplo, si esperas un MRUA, puedes intentar ajustar una ecuación de posición (p = p0 + v0*t + 0.5*a*t^2)
# a tus datos de 'posiciones_x_metros' vs 'tiempo' usando métodos de regresión (ej. numpy.polyfit).

from scipy.optimize import curve_fit

def modelo_mrua(t, p0, v0, a):
    return p0 + v0 * t + 0.5 * a * t**2

# Asegúrate de que 'tiempo' y 'posiciones_x_metros' tengan datos válidos
if len(tiempo) > 0 and len(posiciones_x_metros) > 0:
    try:
        p_opt, p_cov = curve_fit(modelo_mrua, tiempo, posiciones_x_metros, p0=[0, 0, 0])
        p0_estimado, v0_estimado, a_estimada = p_opt

        print(f"Parámetros MRUA estimados: p0={p0_estimado:.2f}m, v0={v0_estimado:.2f}m/s, a={a_estimada:.2f}m/s²")

        # Graficar el modelo teórico junto con los datos experimentales para comparar.
        plt.figure(figsize=(12, 6))
        plt.plot(tiempo, posiciones_x_metros, 'b.', label='Datos Experimentales')
        plt.plot(tiempo, modelo_mrua(tiempo, *p_opt), 'r-', label='Modelo MRUA Ajustado')
        plt.title('Comparación de Posición Experimental y Modelo MRUA')
        plt.xlabel('Tiempo (s)')
        plt.ylabel('Posición (m)')
        plt.legend()
        plt.grid(True)
        plt.show()

    except RuntimeError as e:
        print(f"Error al realizar el ajuste de curva: {e}")
        print("Esto puede ocurrir si los datos no se ajustan bien al modelo o si hay muy pocos puntos.")
else:
    print("No hay suficientes datos de tiempo o posición para realizar el ajuste de curva.")